#!/bin/bash
# ################################################################################################ #
# MetaStack Solutions Ltd.                                                                         #
# ################################################################################################ #
# Microsoft Linker Cygwin PATH Munging Script                                                      #
# ################################################################################################ #
# Copyright (c) 2015, 2016, 2018 MetaStack Solutions Ltd.                                          #
# ################################################################################################ #
# Author: David Allsopp                                                                            #
# 23-Dec-2015                                                                                      #
# ################################################################################################ #
# Redistribution and use in source and binary forms, with or without modification, are permitted   #
# provided that the following two conditions are met:                                              #
#     1. Redistributions of source code must retain the above copyright notice, this list of       #
#        conditions and the following disclaimer.                                                  #
#     2. Neither the name of MetaStack Solutions Ltd. nor the names of its contributors may be     #
#        used to endorse or promote products derived from this software without specific prior     #
#        written permission.                                                                       #
#                                                                                                  #
# This software is provided by the Copyright Holder 'as is' and any express or implied warranties  #
# including, but not limited to, the implied warranties of merchantability and fitness for a       #
# particular purpose are disclaimed. In no event shall the Copyright Holder be liable for any      #
# direct, indirect, incidental, special, exemplary, or consequential damages (including, but not   #
# limited to, procurement of substitute goods or services; loss of use, data, or profits; or       #
# business interruption) however caused and on any theory of liability, whether in contract,       #
# strict liability, or tort (including negligence or otherwise) arising in any way out of the use  #
# use of this software, even if advised of the possibility of such damage.                         #
# ################################################################################################ #

# Ensure that the Microsoft Linker isn't being messed up by /usr/bin/link
if [ "$(link --version 2>/dev/null | sed -ne "1s/Microsoft (R) Incremental Linker//p")" != "" ] ; then
  echo "link already refers to the Microsoft Linker">&2
  exit 0
fi

IFS=:
T=
FOUND=0
FIRST=1
for i in $PATH
do
  if [ $FIRST -eq 1 ] ; then
    T="$i"
    FIRST=0
  else
    if [ $FOUND -eq 0 -a -x $i/link ] && [ "$($i/link --version 2>/dev/null | sed -ne "1s/Microsoft (R) Incremental Linker//p")" != "" ] ; then
      FOUND=1
      T="$i:$T"
      PROM=$i
    else
      T="$T:$i"
    fi
  fi
done
unset IFS

if [ $FOUND -eq 0 ] ; then
  echo The Microsoft Linker was not found in any of the PATH entries!>&2
  exit 1
else
  echo "$PROM moved to the front of \$PATH">&2
  echo export PATH=\"$T\"
fi
