#!/usr/bin/env bash
# ################################################################################################ #
# MetaStack Solutions Ltd.                                                                         #
# ################################################################################################ #
# Microsoft Linker Cygwin PATH Munging Script                                                      #
# ################################################################################################ #
# Copyright (c) 2015, 2016, 2018, 2019, 2020, 2021 MetaStack Solutions Ltd.                        #
# Copyright (c) 2023 Samuel Hym                                                                    #
# ################################################################################################ #
# Author: David Allsopp                                                                            #
# 23-Dec-2015                                                                                      #
# ################################################################################################ #
# Redistribution and use in source and binary forms, with or without modification, are permitted   #
# provided that the following two conditions are met:                                              #
#     1. Redistributions of source code must retain the above copyright notice, this list of       #
#        conditions and the following disclaimer.                                                  #
#     2. Neither the name of MetaStack Solutions Ltd. nor the names of its contributors may be     #
#        used to endorse or promote products derived from this software without specific prior     #
#        written permission.                                                                       #
#                                                                                                  #
# This software is provided by the Copyright Holder 'as is' and any express or implied warranties  #
# including, but not limited to, the implied warranties of merchantability and fitness for a       #
# particular purpose are disclaimed. In no event shall the Copyright Holder be liable for any      #
# direct, indirect, incidental, special, exemplary, or consequential damages (including, but not   #
# limited to, procurement of substitute goods or services; loss of use, data, or profits; or       #
# business interruption) however caused and on any theory of liability, whether in contract,       #
# strict liability, or tort (including negligence or otherwise) arising in any way out of the use  #
# of this software, even if advised of the possibility of such damage.                             #
# ################################################################################################ #

# Ensure that the Microsoft Linker isn't being shadowed by /usr/bin/link
# We expect the Microsoft Linker to be in the same directory as the C compiler

if ! clpath="$(command -v cl)" ; then
  echo "The Microsoft C compiler was not found in any of the PATH entries!">&2
  exit 1
fi
clpath="${clpath%/*}"

if ! linkpath="$(command -v link)" ; then
  echo "The Microsoft Linker was not found in any of the PATH entries!">&2
  exit 1
fi

if [[ ${linkpath%/*} = "$clpath" ]]; then
  echo "link already refers to the Microsoft Linker">&2
  exit 0
fi

NEWPATH="$clpath"
IFS=:
for i in $PATH
do
  if [[ $i != "$clpath" ]]; then
    NEWPATH="$NEWPATH:$i"
  fi
done
unset IFS

echo "$clpath moved to the front of \$PATH">&2
echo "export PATH='"${NEWPATH//\'/\'\"\'\"\'}"'"
